logging-to-file = true
enable-magisk-update = false

[YT]
build-mode = "apk"
excluded-patches = "'Return YouTube Dislike' 'Swipe controls' 'Enable debugging' 'Announcements'"
version = "auto"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"

[YT-EX]
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
build-mode = "apk"
excluded-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube' 'Return YouTube Dislike' 'Swipe controls'"
version = "auto"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
