logging-to-file = true
enable-magisk-update = false

[YT]
patches-source = "inotia00/revanced-patches"
integrations-source = "inotia00/revanced-integrations"
cli-source = "inotia00/revanced-cli"
rv-brand = "REV-EX"
build-mode = "apk"
excluded-patches = "'Custom branding icon YouTube' 'Custom branding name YouTube' 'Return YouTube Dislike' 'Swipe controls'"
version = "auto"
apkmirror-dlurl = "https://apkmirror.com/apk/google-inc/youtube/"
